id: I38B140D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:02:13+00:00'
last_modified: '2022-06-09T05:18:50.709615+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17946
  title: དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལཱུ་ཨི་པའི་ལུགས་ཀྱི་བསྐྱེད་རིམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7249':
      image_group_id: I8LS17953
      title: ''
      total_pages: 82
      order: 1
      base_file: 7249.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
