id: I38B140D5
legacy_id: P008217
ocr_import_info:
  bdrc_scan_id: W8LS17946
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T21:01:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:05:00.377151+00:00'
last_modified: 2022-09-04 12:05:06.010035
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17946
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17946
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལཱུ་ཨི་པའི་ལུགས་ཀྱི་བསྐྱེད་རིམ།
  author: པཎ་ཆེན་བློ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6013854251011613
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I8LS17953:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17953
      total_pages: 82
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17953.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.6013854251011613
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
