id: P008217
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17946
  title: དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལཱུ་ཨི་པའི་ལུགས་ཀྱི་བསྐྱེད་རིམ།
  author: ''
  volumes:
    1383185b9f1e4af08dab9631f34a45e9:
      image_group_id: I8LS17953
      title: ''
      volume_number: 1
      total_pages: 82
